name: Automagically bundle Canary ISO
on:
  push:
    branches:
      - master
jobs:
  tagged-release:
    name: "Canary"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Install dependencies"
        run: sudo apt install build-essential clang lld nasm make grub-pc-bin xorriso
      - name: "Clone FWBuild"
        run: git clone https://github.com/Firework-OS/FWBuild
      - name: "Build & Run FWBuild to create ISO"
        run: cd FWBuild && make TARGET=Release && cd build && ./FireworkBuild -release
      - name: "Create Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
            out/Release/Firework.iso
