name: Automagically bundle release ISO
on:
  push:
    tags:
      - "*"
      - "!*-canary*"
jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Install dependencies"
        run: sudo apt install build-essential clang-9 lld-9 nasm make grub-pc-bin xorriso mtools && alias clang++=clang++-9
      - name: "Clone FWBuild"
        run: git clone https://github.com/Firework-OS/FWBuild
      - name: "Build & Run FWBuild to create ISO"
        run: cd FWBuild && make TARGET=Release && cd build && ./FireworkBuild -release
      - name: "Create Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ./out/Release/Firework.iso
